apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: workloadName
  namespace: nameSpace
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: workloadName
spec:
  build:
    env:
    - name: BP_JVM_VERSION
        value: "javaVersion"
  params:
  - name: buildServiceBindings
    value:
    - apiVersion: v1
      kind: Secret
      name: settings-xml
  - name: gitops_ssh_secret
    value: https-ca-credentials
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: https://github.com/chiupick86/tanzu-java-web-app
      ref:
        branch: main
